### ISSUE TITLE
Deprecate converters, move to own repo

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-server#1457]
@dcolligan I believe these should be in the client. Opinions?

https://github.com/ga4gh/server/blob/master/ga4gh/cli/ga2sam.py
https://github.com/ga4gh/server/blob/master/ga4gh/cli/ga2vcf.py
https://github.com/ga4gh/server/blob/master/ga2vcf_dev.py
https://github.com/ga4gh/server/blob/master/ga2sam_dev.py
https://github.com/ga4gh/server/blob/db3f7bd35944b7d0f510c62760eaa071bf53d7d8/tests/unit/test_converters.py
https://github.com/ga4gh/server/blob/master/ga4gh/converters.py

They're all client side applications I believe.

**Comment by dcolligan** [comment]
I was thinking about this, too... I could see an argument either way.  I say we hold off on it for the moment.  We can't do it without at least some refactoring, since `converters.py` imports some things from `datamodel`.  Also the tests use some server code as well.  Let's wait until after #1449 is fixed, at least.

**Comment by david4096** [comment]
No argument here! It looks to me like the parts of the datamodel it uses are just bytemaps for all the SAM flags. Those seem like they could be moved to common easily.

**Comment by dcolligan** [comment]
A few things:

1) Moving the converters to the client repo would have us either have us not test the converters fully in the client repo, and keep the tests (which depend on server) in server, or import the server package in client for the purpose of testing.  I suppose either is possible.

2) The flag classes in datamodel can not be moved to common because they have a dependency on the protocol, which lives in schemas.  The lowest we could push them down, therefore, would be to schemas.  Does it make sense to have these classes in the schemas repo?  I could see arguments either way.

3) How does the potential moving of the datamodel to its own repo affect this issue?

**Comment by david4096** [comment]
Thanks @dcolligan!

1. My preference is: import the server in the client dev-requirements. It's actually quite nice that we can ship a fully functional server for test.
2. Which flags module? The read SAM flags? I think that it makes sense to provide functions that convert byte values to protobuf enum, which is not necessarily how you might use the feature in the server. Also, in general, for esoteric values like this that only take a few lines, one can err on the side of redundancy.
3. I think since the converters decouple via the client, it would simply change the testing apparatuses. If we put ga4gh-pysam into it's own repository then tests of the pysam transalation feature of the server would have to specifically import it. But you'll still have to import a whole server in order to test it.

It's clear the converters are a different piece of software that depend on the client and pysam and don't need to ship with the server. I suggest moving them to their own repo and testing them apart from the rest of the stack.

Either way, if you're going about this, I would probably just remove ga2vcf completely, it's almost a no-op that we are testing for in Travis.

As an aside, by moving the datamodel out, we have given ourselves the ability to write another piece of software that performs conversion directly via the datamodel, as opposed to over HTTP. I believe this is valuable as it provides developers the ability to develop software that uses our serialization over other protocols.

**Comment by dcolligan** [comment]
Actually, is anyone using the converters?  Do we find them a useful tool at the moment?  It might make just as much sense to remove them from the code base if no one is using them.

If we don't, I'm not sure it makes sense to create another repository just for the converters.  I think we should minimize the number of repositories to the extent possible, since each one we creates adds some admin overhead.

**Comment by david4096** [comment]
Remove them and bring them back as their own software when they work properly. I think people will use this feature if it works.

**Comment by saupchurch** [comment]
I think in general the converters are a useful tool to have.  the downstream game is one of data formats and it is quite easy to see a user have something that only reads VCF as input.  They would then be faced with writing their own converter or just not using GA4GH sourced data.  They definitely shouldn't be in server (at least the ga -> misc ones) but I'm not sure client is the correct place.  What is the vision for ga4gh-client?  Is it a reference client for the reference server?  Or is it something more general like a go to shop for the end user?  A thought: how tightly coupled are these converters to the implementation of the schema?  Would these be something that might actually live in the `tools` directory of `ga4gh-schemas`?

**Comment by david4096** [comment]
I believe we will end up using the client and pysam for the converters and so they wouldn't live with the schemas.

Updated the title to reflect that they should be their own software.

**Comment by david4096** [comment]
Closed with https://github.com/ga4gh/ga4gh-server/pull/1610
