### ISSUE TITLE
Rename readthedocs tag for consistency

### ISSUE THREAD

**Issue by dcolligan** [ga4gh/ga4gh-server#1591]
Rename to `ga4gh-server` from `ga4gh-reference-implementation`

As discussed in #1585

**Comment by kozbo** [comment]
This change makes sense though it pulls a long thread. There are many places where the `ga4gh-reference-server` link is made. Can we leave a redirect link at the old RTD page?

**Comment by david4096** [comment]
Technically yes, but I think it is trivial to maintain both since they're triggered by github. We should work towards a better practice of publishing docs around previous tagged releases, which we started with v0.3.5.

I did a quick look and you can redirect within your subdomain using their tools pretty easily. I think adding a link or doing the redirect some other way is also possible.

https://readthedocs.org/projects/ga4gh-reference-implementation/ could still keep the latest docs using the same webhooks, and https://readthedocs.org/projects/ga4gh-server would be the place to continue to maintain the stable and tagged docs. I think we can close this just by setting up another RTD subdomain attached to this repository.

**Comment by david4096** [comment]
Closing in favor of https://github.com/ga4gh/ga4gh-server/issues/1617
