### ISSUE TITLE
API versioning and Content-Type

### ISSUE THREAD

**Issue by jeromekelleher** [ga4gh/ga4gh-server#526]
Currently, the schemas provide very little specification on the details of the protocol at the HTTP level. One aspect that is currently not well defined is how API versioning occurs and how the HTTP Content-Type is used. This  should, of course, be documented. In the mean time, since we are moving to using the reference server as the de-facto definition of how the protocol is supposed to behave we should agree here on what the correct behaviour is and implement it. Documentation can follow.

In the server, we currently use a HTTP Content-Type of  `application/json` and have a simple URL based API versioning scheme (see #161 for the initial discussion on this). The URL based scheme has proved to be quite awkward in practice, and semantically ambiguous from a REST perspective (are we serving version X of the object, or is this version X of the protocol? Fundamentally, the same URL should point to the same resource, and URL based API versioning breaks this.).  Also, we need to update our Content-Type if we are to serve JSON and a binary encoding of the data (i.e., protobuf).

I propose we follow the approach taken by the MatchMaker team and provide  API version negotiation via the HTTP Accept and Content-Type headers. See [here](https://github.com/ga4gh/mme-apis/blob/develop/search-api.md#versioning) for details on how the MatchMaker API has done this. We don't need to implement version negotiation on the server yet, but we should provide the framework within which it can be done later when the schemas settle down.

So, to be concrete, I would like to
1. Remove the API version prefix from our URLs;
2. Change the Content-Type to something like `application/ga4gh.v0.6+json` and `application/ga4gh.v0.6+proto`

Any thoughts/objections? @diekhans, what do you think of this? 

@calbach, how does Google manage this? Do you agree we should adopt a common approach to content type negotiation and API versioning?

**Comment by diekhans** [comment]
I am adding a section on API version negotiation to the
streaming protocol specification.

**Comment by diekhans** [comment]
One issue, which I am not finding any good guidance on is how to
specify version matching in accepts header.

So lets say we use a 3-part version number:
<major>.<minor>.<bugfix>.  Backwards and forwards compatibility
is assumed within a minor version but not between major ones.

So lets say we have releases version 1.1 and there is a bug fix
in 1.1 that is needed.2.  We want to be able to accept version
1.1.2 or greater, but not version 2.*, which might not be
compatible.

Any ideas on specifying this in request headers?  I am surprised
to not find this as a commonly address issue.

**Comment by jeromekelleher** [comment]
I guess the client sends an Accept header ``application/ga4gh.v1.1.2+json``. If the server can support 1.1.2 (or later) it fulfils the request with Content-Type set appropriately, and if not it returns a HTTP 406. The matchmaker document I linked above says essentially this, and seems pretty sensible.

The semantics of this are a bit tricky. Perhaps initially we should just stipulate an exact match at the 2 digit level, which would at least give users a good error message when they try to connect to a server with a different API version to their client.

**Comment by calbach** [comment]
The approach for Google APIs is to change the URL base path for major version revisions. Anything else is considered to be a minor or bugfix revision. A major version release generally involves large breaking changes to the API, including URLs and renaming, so it's not unreasonable to include this in the URL. I don't know whether one would expect a single URL to multiplex two major versions of the API.

For us, there is only a single production version of the implementation being served at a given time, and its version will always be >= than the public API and client libraries, for which we control the release. This model clearly doesn't carry over 1:1 to GA4GH where there are multiple implementations/clients at different versions. The approach you've described sounds reasonable modulo perhaps the bugfix version number (this is more like a detail of the server implementation, rather than something tied to the API definition).

We should be careful to have reasonable behavior in the degenerate case where a server/client only speaks `application/json`. I haven't dug too deeply yet, but I think that fully supporting your proposed scheme would require jumping through some non-trivial hoops on our end and I can imagine that other clients/servers would also experience difficulties. For example, we have clients who use our API without direct knowledge of the GA4GH and we utilize a lot of common infrastructure on the server and client - being strict about the requirement of a specific content-type on client or server would be a relatively invasive change.

For protobuf, we used to communicate this via a query param `?alt=proto` and we would return a content type of `application/x-protobuf`.

**Comment by jeromekelleher** [comment]
Thanks for this @calbach, this is very encouraging. I agree with you about the bugfix number: two digit precision is surely enough for API versioning. I agree with you also about making sure that degenerate case of JSON only is handled cleanly in a well defined way --- how about we default to JSON at the latest API version, unless otherwise specified via the ``Accept`` headers?

**Comment by IanRogers-LShift** [comment]
The python implementation of semantic versioning could be useful here https://pypi.python.org/pypi/semantic_version

It seems sensible to encode at most the first two parts of the server version in the url. Perhaps also add a /supports url (or some such, with no version number) which a client can interrogate to discover a common version.

**Comment by david4096** [comment]
The schemas now include a version number in the paths, however, the content-type negotiation hasn't been specified.   https://github.com/ga4gh/schemas/blob/master/src/main/proto/ga4gh/bio_metadata_service.proto#L17 .

**Comment by david4096** [comment]
Propose that discussions of content-type happens at the schemas level.
